### ISSUE TITLE
Python version problems

### ISSUE THREAD

**Issue by AndreasAlbert** [clelange/hepdata_lib#32]
There is a versioning problem somewhere.

* When I try to install on lxplus, I run into the error below. 

* This is the same error that kills our [readthedocs build](https://readthedocs.org/projects/hepdata-lib/builds/7280279/), so it is not lxplus specific.

```
# Enable python 27
$ scl enable python27 bash
$ python -V
Python 2.7.3

# Make PyROOT work
$ . /afs/cern.ch/sw/lcg/external/gcc/4.9/x86_64-slc6-gcc49-opt/setup.sh
$ . /afs/cern.ch/sw/lcg/app/releases/ROOT/6.06.06/x86_64-slc6-gcc49-opt/root/bin/thisroot.sh

# Install from local repo copy
$ python -m pip install -e hepdata_lib/ --user

Obtaining file:///afs/cern.ch/work/a/aalbert/public/2018-06-07_hepdata_monojet/hepdata_lib
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/afs/cern.ch/work/a/aalbert/public/2018-06-07_hepdata_monojet/hepdata_lib/setup.py", line 43, in <module>
        'Source': 'https://github.com/clelange/hepdata_lib',
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
        replace_conflicting=True,
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 770, in resolve
        replace_conflicting=replace_conflicting
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1053, in best_match
        return self.obtain(req, installer)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in obtain
        return installer(requirement)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
        return cmd.easy_install(req)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 699, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 884, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1152, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1140, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with Error: typed_ast only runs on Python 3.3 and above.
    
    ----------------------------------------
```

**Comment by AndreasAlbert** [comment]
The last working RTD build was [here](https://readthedocs.org/projects/hepdata-lib/builds/7239768/) with commit 2e3c0b3b4d18d339da63163a56b3b3d725a7ddc5

However, if I use that commits on lxplus, I still get the same error (see below). What is `typed_ast` and why are we installing it?

```
$ python -m pip  install git+https://github.com/clelange/hepdata_lib.git@2e3c0b3b4d18d339da63163a56b3b3d725a7ddc5
Collecting git+https://github.com/clelange/hepdata_lib.git@2e3c0b3b4d18d339da63163a56b3b3d725a7ddc5
  Cloning https://github.com/clelange/hepdata_lib.git (to revision 2e3c0b3b4d18d339da63163a56b3b3d725a7ddc5) to /tmp/aalbert/pip-req-build-W4Pf5Z
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/aalbert/pip-req-build-W4Pf5Z/.eggs/wrapt-1.10.11-py2.7-linux-x86_64.egg
    Searching for typing
    Reading https://pypi.org/simple/typing/
    Downloading https://files.pythonhosted.org/packages/0d/4d/4e5985d075d241d686a1663fa1f88b61d544658d08c1375c7c6aac32afc3/typing-3.6.4-py2-none-any.whl#sha256=b2c689d54e1144bbcfd191b0832980a21c2dbcf7b5ff7a66248a60c90e951eb8
    Best match: typing 3.6.4
    Processing typing-3.6.4-py2-none-any.whl
    Installing typing-3.6.4-py2-none-any.whl to /tmp/aalbert/pip-req-build-W4Pf5Z/.eggs
    
    Installed /tmp/aalbert/pip-req-build-W4Pf5Z/.eggs/typing-3.6.4-py2.7.egg
    Searching for typed-ast
    Reading https://pypi.org/simple/typed-ast/
    Downloading https://files.pythonhosted.org/packages/52/cf/2ebc7d282f026e21eed4987e42e10964a077c13cfc168b42f3573a7f178c/typed-ast-1.1.0.tar.gz#sha256=57fe287f0cdd9ceaf69e7b71a2e94a24b5d268b35df251a88fef5cc241bf73aa
    Best match: typed-ast 1.1.0
    Processing typed-ast-1.1.0.tar.gz
    Writing /tmp/aalbert/easy_install-8YZeyI/typed-ast-1.1.0/setup.cfg
    Running typed-ast-1.1.0/setup.py -q bdist_egg --dist-dir /tmp/aalbert/easy_install-8YZeyI/typed-ast-1.1.0/egg-dist-tmp-NrzqDd
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/aalbert/pip-req-build-W4Pf5Z/setup.py", line 43, in <module>
        'Source': 'https://github.com/clelange/hepdata_lib',
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
        replace_conflicting=True,
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 770, in resolve
        replace_conflicting=replace_conflicting
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1053, in best_match
        return self.obtain(req, installer)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in obtain
        return installer(requirement)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
        return cmd.easy_install(req)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 699, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 884, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1152, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/afs/cern.ch/user/a/aalbert/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1140, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with Error: typed_ast only runs on Python 3.3 and above.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/aalbert/pip-req-build-W4Pf5Z/
```

**Comment by AndreasAlbert** [comment]
The problem is with pylint, which starting with version 2.0 does not support python 2.7 anymore (see e.g. [here](https://pylint.readthedocs.io/en/latest/faq.html). pylint 1.8 and 1.9 should still do it, but those are not installable on pip?

**Comment by AndreasAlbert** [comment]
Okay, everything works out if I just manually do
`pip install "pylint<2.0.0"`
before installing hepdata_lib.  I would have thought that I can get the `setup.py` to do this by adding `"pylint<2.0.0"` to `install_requires`. This doesn't seem to work.

@clelange Any idea?
